<a href="https://colab.research.google.com/github/Kunal988-gif/DataScience/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
file = pd.read_csv("./student_data.csv", sep = ',')
print(file)

print("\n")

df = pd.DataFrame(file)
print(df)

print("\n")

f = df.head(10)
print(f)

t = df.tail(10)
print(t)

      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7
1               4          69            5               3
2              11          60            7               6
3               8          99            9               8
4               5          52            8               6
...           ...         ...          ...             ...
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
0                        10              62      100.00           Placed
1                         8              56      100.00           Placed
2                        10              45      100.00           Placed
3                         4              55       90.17           Placed
4                         8              40       78.82           Placed
...                     ...             ...         ...              ...
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

[10000 rows x 8 columns]


      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7
1               4          69            5               3
2              11          60            7               6
3               8          99            9               8
4               5          52            8               6
...           ...         ...          ...             ...
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
0                        10              62      100.00           Placed
1                         8              56      100.00           Placed
2                        10              45      100.00           Placed
3                         4              55       90.17           Placed
4                         8              40       78.82           Placed
...                     ...             ...         ...              ...
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

[10000 rows x 8 columns]


   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7
1            4          69            5               3
2           11          60            7               6
3            8          99            9               8
4            5          52            8               6
5            7          40            9              10
6           10          40            4              11
7            3          86            7               3
8            7          72            8               5
9           11          77            4               9

   assignments_completed  previous_score  exam_score placement_status
0                     10              62      100.00           Placed
1                      8              56      100.00           Placed
2                     10              45      100.00           Placed
3                      4              55       90.17           Placed
4                      8              40       78.82           Placed
5                      0              60       72.33           Placed
6                      9              50       98.12           Placed
7                      7              85      100.00           Placed
8                     18              48       96.81           Placed
9                     15              69      100.00           Placed
      study_hours  attendance  sleep_hours  internet_usage  \
9990            4          72            8               6
9991           10          93            7              11
9992            5         100            9               2
9993           10          86            9               9
9994            4          53            7               8
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
9990                      4              72       86.47           Placed
9991                      3              53       97.90           Placed
9992                      9              62      100.00           Placed
9993                     15              63      100.00           Placed
9994                     10              71       85.02           Placed
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

In [ ]:
import pandas as pd
dict = {
    'name' : ['kunnu', 'brownie','pankhuri','Jack'],
    'age' : [19, 19, 19, 19],
    'roll no' : [44, 33, 52, 71]

}

df = pd.DataFrame(dict)
print(df)

print('\n')

df1 = pd.DataFrame(dict, index = ['a','b','c','d'])
display(df1)

       name  age  roll no
0     kunnu   19       44
1   brownie   19       33
2  pankhuri   19       52
3      Jack   19       71

       name  age  roll no
a     kunnu   19       44
b   brownie   19       33
c  pankhuri   19       52
d      Jack   19       71

In [ ]:
df = pd.read_csv("student_data.csv")
#print(df)
#print('\n')

df.head(10)
df.tail()
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [38]:
df = pd.read_csv('student_data.csv')
df.tail(3)




df.index


df[['study_hours','internet_usage']]

df.iloc[0:5]

df.loc[df['study_hours'] == 11, ['study_hours','sleep_hours']].iloc[4:8]

df2 = df.loc[df['study_hours'] == 11]

df2[['study_hours']]


#difference
df3 = df.loc[df['study_hours'] == 11]

df.loc[4]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [46]:
df = pd.read_csv('student_data.csv')
df.loc[df['assignments_completed'] == 8,['assignments_completed']].iloc[1: 3]

    assignments_completed
4                       8
13                      8

In [56]:
df = pd.read_csv('student_data.csv')
df[df["assignments_completed"] > 3]

df['age'] = 28;

In [63]:
df = pd.read_csv('student_data.csv')
#df = df.rename(columns = {'assignments_completed' : 'assign_completed'})

#if you want to change it directly , you can use 'inplace'

df.rename(columns = {'assignments_completed' : 'assign_completed'}, inplace = True)
df.head()


df.drop(0, axis = 0, inplace = True)
df.head()

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
5,7,40,9,10,0,60,72.33,Placed

In [77]:
dct = {
    'name' : ['kunnu', 'brownie','pankhuri','sagar'],
    'age' : [203, 209, 809, 19999],
    'roll no' : [33,3546, 646, 35353],
    'college' : None
}


df = pd.DataFrame(dct)
df.drop('age', axis = 1, inplace = True)


#df.dropna(axis = 1, inplace = True)
#df

#df.fillna(0, inplace = True)
#df

#df.isnull()

/tmp/ipykernel_1473/1856044807.py:16: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(0, inplace = True)

    name  roll no  college
0  False    False    False
1  False    False    False
2  False    False    False
3  False    False    False